export type CatchPhraseClue = {
  id: string;
  text: string;
};

const CLUE_TEXTS: readonly string[] = [
  "Peanut butter",
  "Microwave oven",
  "Road trip",
  "Snow day",
  "Movie trailer",
  "Credit card",
  "Fire drill",
  "Birthday candle",
  "Dance floor",
  "Video game",
  "Pizza delivery",
  "Homework pass",
  "Board game night",
  "Photo booth",
  "Weekend plans",
  "Phone charger",
  "Traffic jam",
  "Coffee mug",
  "Alarm clock",
  "Roller coaster",
  "First impression",
  "Group chat",
  "Broken umbrella",
  "Pumpkin spice",
  "Family reunion",
  "Learning curve",
  "Paper cut",
  "Kitchen sink",
  "Shopping cart",
  "Scavenger hunt",
  "Magic trick",
  "Window seat",
  "Hotel lobby",
  "Gym membership",
  "Public speaking",
  "Road sign",
  "Math quiz",
  "Laundry basket",
  "Picnic table",
  "Camp fire",
  "School cafeteria",
  "Lucky charm",
  "Red carpet",
  "Movie premiere",
  "Thunderstorm",
  "Vacation photos",
  "Ghost story",
  "Science fair",
  "Wireless headphones",
  "House key",
  "Broken pencil",
  "Toothbrush",
  "Hair dryer",
  "Dishwasher",
  "Carpool lane",
  "Elevator music",
  "Window shopping",
  "Chocolate milk",
  "Book club",
  "Sneaker collection",
  "Roadside diner",
  "Rain boots",
  "Sunglasses",
  "Gym class",
  "Weather forecast",
  "Swimming pool",
  "Beach towel",
  "Water bottle",
  "Flashlight",
  "Desk lamp",
  "Camping tent",
  "Sleeping bag",
  "Power outage",
  "School bus",
  "Traffic light",
  "Skateboard",
  "Phone call",
  "Text message",
  "Pet hamster",
  "Dog leash",
  "Cat nap",
  "Bird feeder",
  "Cooking class",
  "Piano lesson",
  "Guitar solo",
  "Choir concert",
  "Lunch break",
  "Office party",
  "Calendar reminder",
  "Zip code",
  "Post office",
  "Train station",
  "Airport security",
  "Window washer",
  "Ice cream truck",
  "Farmer's market",
  "Garden hose",
  "Movie theater",
  "Karaoke night",
  "Treasure map",
  "Puzzle piece",
  "Jigsaw puzzle",
  "Chess match",
  "Soccer practice",
  "Baseball glove",
  "Basketball hoop",
  "Tennis court",
  "Golf cart",
  "Bowling alley",
  "Ski lift",
  "Surf board",
  "Fishing pole",
  "Toy store",
  "Birthday party",
  "Wedding ring",
  "Baby shower",
  "Graduation cap",
  "Science fiction",
  "Comic book",
  "Library card",
  "Bookmark",
  "News headline",
  "Breaking news",
  "Flash sale",
  "Coupon code",
  "Online order",
  "Wi-Fi password",
  "Password reset",
  "Phone battery",
  "Bluetooth speaker",
  "Laptop charger",
  "Cloud storage",
  "Keyboard shortcut",
  "Screen saver",
  "Mouse pad",
  "Video call",
  "Mute button",
  "Volume control",
  "Emergency exit",
  "Speed limit",
  "Crosswalk",
  "Gas station",
  "Car wash",
  "Flat tire",
  "Seat belt",
  "Driving test",
  "Parallel parking",
  "Movie spoiler",
  "Plot twist",
  "Theme song",
  "Final exam",
  "Class project",
  "Field trip",
  "Summer break",
  "Spring cleaning",
  "Winter coat",
  "Autumn leaves",
  "Clock tower",
  "Town square",
  "Street parade",
  "Fireworks show",
  "New year countdown",
  "Photo album",
  "Souvenir shop",
  "Room service",
  "Front desk"
];

export const CATCH_PHRASE_CLUES: readonly CatchPhraseClue[] = CLUE_TEXTS.map((text, index) => ({
  id: `phrase-${String(index).padStart(4, "0")}`,
  text
}));

export function pickCatchPhraseClue(usedIds: readonly string[]): CatchPhraseClue | null {
  const used = new Set(usedIds);
  const pool = CATCH_PHRASE_CLUES.filter((c) => !used.has(c.id));
  const source = pool.length > 0 ? pool : [...CATCH_PHRASE_CLUES];
  if (source.length === 0) {
    return null;
  }
  return source[Math.floor(Math.random() * source.length)]!;
}
