import type { MadlibsBlankPrompt } from "../../shared/contracts";

export type MadlibSegment =
  | { kind: "text"; text: string }
  | { kind: "blank"; prompt: MadlibsBlankPrompt };

export type MadlibTemplate = {
  id: string;
  title: string;
  segments: readonly MadlibSegment[];
};

const text = (value: string): MadlibSegment => ({ kind: "text", text: value });
const blank = (prompt: MadlibsBlankPrompt): MadlibSegment => ({ kind: "blank", prompt });

export const MADLIBS_TEMPLATES: readonly MadlibTemplate[] = [
  {
    id: "office-email",
    title: "Office Email",
    segments: [
      text("Hello team, this is a friendly reminder that our quarterly planning summit starts at sunrise in the "),
      blank("place"),
      text(". Please bring your personal "),
      blank("noun"),
      text(", one "),
      blank("adjective"),
      text(" idea for growth, and exactly "),
      blank("number"),
      text(" sticky notes. We will open with a guided "),
      blank("verb"),
      text(" session, then split into pairs to map risks involving "),
      blank("plural noun"),
      text(". At lunch, "),
      blank("person"),
      text(" will present a case study about morale, snacks, and the unexpected role of "),
      blank("food"),
      text(" in project velocity. If your laptop makes a "),
      blank("silly word"),
      text(" noise, visit Tech Corner immediately. Our final deliverable is a one-page plan that feels "),
      blank("emotion"),
      text(", practical, and impossible to ignore. Thank you for your attention and your commitment to making this the most memorable planning meeting in company history.")
    ]
  },
  {
    id: "road-trip",
    title: "Road Trip",
    segments: [
      text("We left town before dawn with a trunk full of "),
      blank("plural noun"),
      text(", a playlist labeled "),
      blank("silly word"),
      text(", and a promise to reach "),
      blank("place"),
      text(" by sunset. At the first gas station, we bought "),
      blank("food"),
      text(" and accidentally locked the keys next to a plastic "),
      blank("noun"),
      text(". Somehow, "),
      blank("person"),
      text(" opened the door with a "),
      blank("body part"),
      text(" and pure confidence. Back on the highway, a "),
      blank("animal"),
      text(" ran beside us for almost "),
      blank("number"),
      text(" miles while we argued about the best way to "),
      blank("verb"),
      text(" at rest stops. By evening, everyone was tired, loud, and weirdly optimistic. We rolled into town looking "),
      blank("adjective"),
      text(", took a group photo, and agreed the trip was a complete disaster that we absolutely had to repeat next month.")
    ]
  },
  {
    id: "cooking-disaster",
    title: "Cooking Disaster",
    segments: [
      text("Tonight I attempted to host a refined dinner party, but the recipe opened with the instruction to "),
      blank("verb"),
      text(" a cast-iron "),
      blank("noun"),
      text(" until it looked "),
      blank("adjective"),
      text(". I confidently "),
      blank("past tense verb"),
      text(" the "),
      blank("food"),
      text(" and added "),
      blank("number"),
      text(" spoons of "),
      blank("noun"),
      text(" because the internet called it a flavor amplifier. Instead, smoke alarms began a synchronized "),
      blank("verb"),
      text(" performance, my neighbor banged on the door, and my "),
      blank("animal"),
      text(" stole the garnish directly from the counter. Trying to recover, I tossed in extra "),
      blank("food"),
      text(" and whispered encouraging words to the saucepan. The final dish had a texture like "),
      blank("body part"),
      text(" and a smell that made everyone feel "),
      blank("emotion"),
      text(". We ordered takeout, toasted my courage, and agreed this meal would be remembered for years, mostly as a warning.")
    ]
  },
  {
    id: "pet-story",
    title: "Pet Story",
    segments: [
      text("Every morning at exactly six, my "),
      blank("animal"),
      text(" jumps onto the bed, stares at my "),
      blank("body part"),
      text(", and refuses to move until I "),
      blank("verb"),
      text(" the kitchen light. Breakfast must be served in a "),
      blank("adjective"),
      text(" bowl beside the sacred "),
      blank("noun"),
      text(", or chaos begins. Yesterday it dragged "),
      blank("plural noun"),
      text(" through the hallway, hid behind the couch, and made a tiny "),
      blank("silly word"),
      text(" sound whenever I approached. By afternoon, "),
      blank("person"),
      text(" visited and suggested we train it with "),
      blank("food"),
      text(" rewards, but the creature outsmarted us by pretending to nap and then sprinting toward "),
      blank("place"),
      text(". At night it curled up like nothing happened, and everyone in the house felt "),
      blank("emotion"),
      text(", amused, and slightly manipulated by twelve pounds of strategic fluff.")
    ]
  },
  {
    id: "weather-report",
    title: "Weather Report",
    segments: [
      text("Good evening from Channel "),
      blank("number"),
      text(" Weather. Tonight in "),
      blank("place"),
      text(", expect a front of "),
      blank("adjective"),
      text(" clouds moving in from the coast, followed by "),
      blank("number"),
      text(" inches of "),
      blank("noun"),
      text(" before midnight. Winds will blow "),
      blank("adverb"),
      text(" enough to relocate porch furniture, small hats, and any unattended "),
      blank("plural noun"),
      text(". Tomorrow morning, commuters should allow extra time if they travel by "),
      blank("noun"),
      text(", especially near "),
      blank("place"),
      text(" where visibility may drop quickly. Our meteorologist, "),
      blank("person"),
      text(", recommends wearing something "),
      blank("color"),
      text(" so rescue teams can find you dramatically in live footage. By afternoon, skies will clear, temperatures will rise, and neighbors will gather to "),
      blank("verb"),
      text(" about how they absolutely predicted this all along.")
    ]
  },
  {
    id: "tech-support",
    title: "Tech Support",
    segments: [
      text("Thank you for contacting premium support. Before we proceed, please confirm the "),
      blank("noun"),
      text(" is plugged in, powered on, and not balanced on a "),
      blank("food"),
      text(". If your screen displays the message "),
      blank("silly word"),
      text(", remain calm and place your "),
      blank("body part"),
      text(" on the keyboard for emotional grounding. Next, click Settings, choose "),
      blank("adjective"),
      text(" Mode, and "),
      blank("verb"),
      text(" the restart icon exactly "),
      blank("number"),
      text(" times. If that fails, our escalation protocol asks you to locate a trusted "),
      blank("person"),
      text(", describe the issue near "),
      blank("place"),
      text(", and then unplug everything for one dramatic minute. Most issues are resolved when users stop opening "),
      blank("plural noun"),
      text(" from unknown senders. If the device still refuses to cooperate, we will schedule a specialist who brings optimism, spare cables, and a suspiciously confident "),
      blank("animal"),
      text(".")
    ]
  },
  {
    id: "gym-resolution",
    title: "Gym Resolution",
    segments: [
      text("This year I promised myself I would "),
      blank("verb"),
      text(" at the gym "),
      blank("number"),
      text(" days each week, track progress in a "),
      blank("noun"),
      text(", and avoid comparing myself to anyone wearing "),
      blank("color"),
      text(" "),
      blank("plural noun"),
      text(". On day one, trainer "),
      blank("person"),
      text(" asked me to warm up with a "),
      blank("adjective"),
      text(" routine that targeted my "),
      blank("body part"),
      text(", my patience, and my ego. By day three I could lift exactly one more "),
      blank("noun"),
      text(" than before, which felt heroic. Every session ended with "),
      blank("food"),
      text(" smoothies and a motivational speech that sounded like a movie trailer. Some mornings I felt "),
      blank("emotion"),
      text(", some mornings I felt tired, but I kept showing up. My real goal is simple: become stronger, laugh more, and stop fearing stairs forever.")
    ]
  },
  {
    id: "coffee-order",
    title: "Coffee Order",
    segments: [
      text("Hi there, can I order a "),
      blank("adjective"),
      text(" latte with "),
      blank("number"),
      text(" pumps of "),
      blank("food"),
      text(", extra foam, and exactly one sprinkle of "),
      blank("color"),
      text(" cinnamon? Also add a side of "),
      blank("plural noun"),
      text(" because I had a morning that required emotional backup. My boss, "),
      blank("person"),
      text(", scheduled six meetings before noon and each one included the phrase "),
      blank("silly word"),
      text(" synergy. While waiting, I tried to "),
      blank("verb"),
      text(" quietly, but the blender sounded like an angry "),
      blank("animal"),
      text(" and everyone turned around. If possible, write my name as "),
      blank("noun"),
      text(" on the cup so I feel mysterious for five minutes. I am heading to "),
      blank("place"),
      text(" after this, and your masterpiece is the only thing standing between me and a complete collapse.")
    ]
  },
  {
    id: "birthday-party",
    title: "Birthday Party",
    segments: [
      text("For my birthday this year, "),
      blank("person"),
      text(" arrived early with a "),
      blank("adjective"),
      text(" cake shaped like a "),
      blank("noun"),
      text(", a playlist of dramatic anthems, and "),
      blank("number"),
      text(" balloons that immediately floated into the ceiling fan. Then "),
      blank("person"),
      text(" tried to "),
      blank("verb"),
      text(" the decorations, but instead released a cloud of "),
      blank("plural noun"),
      text(" over the snack table. Someone spilled "),
      blank("food"),
      text(" on the dance floor, someone else started a conga line to "),
      blank("place"),
      text(", and the neighbors watched from their porch looking "),
      blank("emotion"),
      text(". At cake time, we sang every chorus in a different style, from opera to whisper rap. By midnight the house looked like a parade had collided with a talent show, and it was perfect.")
    ]
  },
  {
    id: "superhero-tagline",
    title: "Superhero Tagline",
    segments: [
      text("I am Captain "),
      blank("noun"),
      text(", sworn defender of "),
      blank("place"),
      text(", protector of lunch breaks, and guardian of all misplaced chargers. By day I work as a "),
      blank("occupation"),
      text(" with a "),
      blank("adjective"),
      text(" smile, but by night my "),
      blank("body part"),
      text(" glows with cosmic energy whenever evil appears. My sidekick, a "),
      blank("animal"),
      text(" named "),
      blank("silly word"),
      text(", rides a "),
      blank("color"),
      text(" scooter and can "),
      blank("verb"),
      text(" through walls if snacks are involved. Together we battle villains who steal "),
      blank("plural noun"),
      text(" and replace them with mildly disappointing versions. Citizens call us when the city feels "),
      blank("emotion"),
      text(", because hope arrives faster than traffic. My mission remains simple: protect the people, save game night, and always return borrowed pens.")
    ]
  },
  {
    id: "job-application",
    title: "Job Application",
    segments: [
      text("Dear Hiring Team, I am applying for the role of Senior "),
      blank("occupation"),
      text(" at your "),
      blank("adjective"),
      text(" organization. Over the past "),
      blank("number"),
      text(" years, I have led projects involving "),
      blank("plural noun"),
      text(", crisis planning, and late-night "),
      blank("verb"),
      text(" sessions before important launches. In my last role at "),
      blank("place"),
      text(", I improved efficiency by replacing meetings with a shared "),
      blank("noun"),
      text(" and weekly check-ins powered by "),
      blank("food"),
      text(". Colleagues describe my leadership style as calm, direct, and occasionally "),
      blank("silly word"),
      text(" when morale is low. I value communication, accountability, and celebrating wins, even tiny ones. If selected, I will bring curiosity, discipline, and a commitment to making every team member feel "),
      blank("emotion"),
      text(" about the work we do together.")
    ]
  },
  {
    id: "zoo-escape",
    title: "Zoo Escape",
    segments: [
      text("At exactly "),
      blank("number"),
      text(" o'clock, a "),
      blank("animal"),
      text(" escaped from the zoo and "),
      blank("past tense verb"),
      text(" straight through "),
      blank("place"),
      text(" carrying a crate of "),
      blank("plural noun"),
      text(". The security team sounded alarms while visitors stood frozen, looking "),
      blank("emotion"),
      text(", until ranger "),
      blank("person"),
      text(" shouted a plan. We formed a line, tossed "),
      blank("food"),
      text(" as a distraction, and slowly guided the runaway toward the old "),
      blank("noun"),
      text(" enclosure. For a moment it paused, tilted its head, and made a "),
      blank("silly word"),
      text(" noise that echoed across the park. Then, with one final dramatic "),
      blank("verb"),
      text(", it stepped back inside the gate. Reporters called it a miracle, children called it awesome, and the staff called it Tuesday.")
    ]
  },
  {
    id: "concert-moment",
    title: "Concert Moment",
    segments: [
      text("The arena lights dropped, the crowd counted down from "),
      blank("number"),
      text(", and the band exploded onto stage with a "),
      blank("adjective"),
      text(" riff played on a glowing "),
      blank("noun"),
      text(". Fans waved "),
      blank("plural noun"),
      text(" in the air while lead singer "),
      blank("person"),
      text(" shouted "),
      blank("silly word"),
      text(" between every chorus. Midway through the set, a giant "),
      blank("animal"),
      text(" mascot rolled out, launched "),
      blank("food"),
      text(" into the front row, and invited everyone to "),
      blank("verb"),
      text(" in perfect rhythm. The floor shook, strangers hugged, and even security looked "),
      blank("emotion"),
      text(" for a second. During the encore, the whole venue sang so loudly that nearby streets in "),
      blank("place"),
      text(" could hear it. We left hoarse, happy, and convinced we had witnessed the loudest masterpiece on earth.")
    ]
  },
  {
    id: "haunted-house",
    title: "Haunted House",
    segments: [
      text("We entered the haunted house at dusk, carrying one "),
      blank("noun"),
      text(" and far too much confidence. The hallway smelled "),
      blank("adjective"),
      text(", portraits blinked when nobody moved, and somewhere upstairs a "),
      blank("animal"),
      text(" scratched at the walls. Then a hidden speaker whispered "),
      blank("silly word"),
      text(", and "),
      blank("person"),
      text(" immediately tried to "),
      blank("verb"),
      text(" through the nearest doorway. In the dining room, plates rattled by themselves and a cold draft touched my "),
      blank("body part"),
      text(" like an icy warning. We found "),
      blank("number"),
      text(" candles around a table set with "),
      blank("food"),
      text(" that looked suspiciously fresh. By the time we reached the attic in "),
      blank("place"),
      text(", everyone was laughing too hard to be scared. The final ghost appeared, bowed politely, and asked us to leave a five-star review.")
    ]
  },
  {
    id: "space-mission",
    title: "Space Mission",
    segments: [
      text("Mission log day "),
      blank("number"),
      text(": Commander "),
      blank("person"),
      text(" confirmed our "),
      blank("noun"),
      text(" is on course for "),
      blank("place"),
      text(". During morning checks, a "),
      blank("adjective"),
      text(" warning light flashed beside the oxygen controls, so engineer team alpha began to "),
      blank("verb"),
      text(" through diagnostics while the autopilot played "),
      blank("silly word"),
      text(" tones at full volume. For lunch we shared "),
      blank("food"),
      text(" packets and watched a "),
      blank("animal"),
      text(" float past the observation window, which nobody could explain. At 1400 hours, we deployed "),
      blank("plural noun"),
      text(" into orbit and recorded spectacular data about cosmic storms. Spirits stayed "),
      blank("emotion"),
      text(" despite the turbulence, and by evening we prepared for landing. If this transmission reaches home, tell everyone the universe is enormous, strange, and absolutely worth exploring.")
    ]
  },
  {
    id: "sports-play-by-play",
    title: "Sports Play-by-Play",
    segments: [
      text("Welcome back to the championship game with only "),
      blank("number"),
      text(" seconds remaining. Quarterback "),
      blank("person"),
      text(" takes the snap, dodges a "),
      blank("adjective"),
      text(" defender, and launches the ball toward the "),
      blank("occupation"),
      text(" near the goal line. The crowd in "),
      blank("place"),
      text(" rises all at once, waving "),
      blank("plural noun"),
      text(" and chanting "),
      blank("silly word"),
      text(" so loudly the broadcast booth shakes. He catches it, stumbles, regains balance with his "),
      blank("body part"),
      text(", and dives over a pile of helmets, hopes, and spilled "),
      blank("food"),
      text(". Touchdown. Fireworks burst, teammates "),
      blank("verb"),
      text(" across the field, and the scoreboard confirms a miracle comeback. Fans cry, laugh, and look "),
      blank("emotion"),
      text(" all at once. This is why we watch sports: for impossible endings that feel scripted by chaos itself.")
    ]
  },
  {
    id: "dating-profile",
    title: "Dating Profile",
    segments: [
      text("Hi, I am the kind of person who enjoys "),
      blank("verb"),
      text(" on weekends, especially when accompanied by "),
      blank("plural noun"),
      text(", good music, and a plan that may or may not work. Friends say I am "),
      blank("adjective"),
      text(", reliable, and weirdly competitive about board games. My ideal first date includes "),
      blank("food"),
      text(", a walk through "),
      blank("place"),
      text(", and a deep conversation about whether a "),
      blank("animal"),
      text(" could run a startup. I work as a "),
      blank("occupation"),
      text(", laugh too loudly at "),
      blank("silly word"),
      text(" jokes, and always carry a backup "),
      blank("noun"),
      text(" in case of emergencies. Looking for someone "),
      blank("emotion"),
      text(" about life, kind to service workers, and brave enough to sing in the car. If that sounds like you, send a message and tell me your most chaotic travel story.")
    ]
  },
  {
    id: "school-announcement",
    title: "School Announcement",
    segments: [
      text("Attention students and staff: this is an official announcement from Principal "),
      blank("person"),
      text(". Due to a "),
      blank("adjective"),
      text(" incident involving the "),
      blank("noun"),
      text(" club and "),
      blank("number"),
      text(" boxes of "),
      blank("food"),
      text(", today's assembly has moved to "),
      blank("place"),
      text(". Please arrive "),
      blank("adverb"),
      text(" and bring "),
      blank("plural noun"),
      text(", and avoid running in the hallways even if you hear "),
      blank("silly word"),
      text(" noises from the science wing. Teachers should escort classes in alphabetical order by "),
      blank("color"),
      text(" folder. If you volunteered to "),
      blank("verb"),
      text(" during the talent showcase, report backstage immediately for microphone checks and emergency glitter removal. We know this schedule change may feel "),
      blank("emotion"),
      text(", but your flexibility keeps our school safe, organized, and surprisingly entertaining.")
    ]
  },
  {
    id: "breaking-news",
    title: "Breaking News",
    segments: [
      text("Breaking news from downtown "),
      blank("place"),
      text(": eyewitnesses report a "),
      blank("adjective"),
      text(" "),
      blank("animal"),
      text(" was seen "),
      blank("verb"),
      text(" near City Hall while carrying a "),
      blank("noun"),
      text(" and wearing "),
      blank("color"),
      text(" "),
      blank("plural noun"),
      text(". Authorities say the creature appeared at "),
      blank("number"),
      text(" a.m., startled commuters, and caused several street musicians to play "),
      blank("silly word"),
      text(" remixes on repeat. Local resident "),
      blank("person"),
      text(" described the scene as both alarming and "),
      blank("emotion"),
      text(", adding that the visitor paused to eat "),
      blank("food"),
      text(" before disappearing behind the courthouse. Officials are urging calm and asking anyone with video footage to submit reports. We will continue following this developing story as experts debate whether this was a prank, a parade rehearsal, or the start of a very strange new era.")
    ]
  },
  {
    id: "fortune-cookie",
    title: "Fortune Cookie",
    segments: [
      text("Your fortune for the week: A "),
      blank("adjective"),
      text(" opportunity will appear when you least expect it, probably near "),
      blank("place"),
      text(" around "),
      blank("number"),
      text(" o'clock. A mysterious "),
      blank("person"),
      text(" will offer you "),
      blank("plural noun"),
      text(" and ask if you are ready to "),
      blank("verb"),
      text(" beyond your comfort zone. Say yes, but keep a "),
      blank("noun"),
      text(" nearby for luck. Midweek, avoid arguments about "),
      blank("food"),
      text(", because the stars predict unnecessary drama and at least one shouted "),
      blank("silly word"),
      text(". By Friday, your confidence will feel "),
      blank("emotion"),
      text(", and an unexpected message from a "),
      blank("animal"),
      text(" enthusiast will make you laugh harder than expected. Trust your instincts, share your wins, and remember: the universe rewards people who show up prepared and curious.")
    ]
  }
];

export const pickMadlibTemplate = (usedTemplateIds: readonly string[]): MadlibTemplate => {
  const unused = MADLIBS_TEMPLATES.filter((template) => !usedTemplateIds.includes(template.id));
  const pool = unused.length > 0 ? unused : MADLIBS_TEMPLATES;
  return pool[Math.floor(Math.random() * pool.length)] ?? pool[0];
};

export const madlibBlankCount = (template: MadlibTemplate): number =>
  template.segments.filter((segment) => segment.kind === "blank").length;

export const fillMadlibTemplate = (template: MadlibTemplate, words: readonly string[]): string => {
  let blankIndex = 0;
  const rendered = template.segments.map((segment) => {
    if (segment.kind === "text") {
      return segment.text;
    }
    const nextWord = words[blankIndex] ?? "";
    blankIndex += 1;
    return nextWord;
  });
  return rendered.join("");
};
