/** Single drawable clue with stable id for deduplication across a session. */
export type PictionaryClue = {
  id: string;
  text: string;
};

const CLUE_TEXTS: readonly string[] = [
  // Animals
  "Penguin",
  "Octopus",
  "Giraffe",
  "Kangaroo",
  "Hedgehog",
  "Flamingo",
  "Sloth",
  "Walrus",
  "Peacock",
  "Platypus",
  "Narwhal",
  "Chameleon",
  "Raccoon",
  "Otter",
  "Llama",
  "Alpaca",
  "Moose",
  "Badger",
  "Beaver",
  "Porcupine",
  // Food & drink
  "Spaghetti",
  "Taco",
  "Sushi",
  "Watermelon",
  "Pancake stack",
  "Ice cream cone",
  "Hot dog",
  "Birthday cake",
  "Avocado toast",
  "Bubble tea",
  "Pizza slice",
  "Donut",
  "Croissant",
  "Popcorn",
  "Banana split",
  "Corn on the cob",
  "Pumpkin pie",
  "Cheeseburger",
  "French fries",
  "Lobster roll",
  // Objects & tools
  "Umbrella",
  "Lighthouse",
  "Telescope",
  "Grandfather clock",
  "Vacuum cleaner",
  "Lawn mower",
  "Snow shovel",
  "Rubber duck",
  "Paper airplane",
  "Kite",
  "Yo-yo",
  "Pogo stick",
  "Trampoline",
  "Skateboard",
  "Roller skates",
  "Fire hydrant",
  "Stop sign",
  "Traffic light",
  "Mailbox",
  "Park bench",
  // Places & landmarks
  "Eiffel Tower",
  "Statue of Liberty",
  "Pyramids of Giza",
  "Big Ben",
  "Golden Gate Bridge",
  "Mount Rushmore",
  "Leaning Tower of Pisa",
  "Taj Mahal",
  "Great Wall of China",
  "Stonehenge",
  "Hollywood sign",
  "Niagara Falls",
  "Grand Canyon",
  "North Pole",
  "Beach umbrella",
  "Camping tent",
  "Igloo",
  "Treehouse",
  "Castle",
  "Haunted house",
  // Actions & phrases
  "Brushing teeth",
  "Riding a bike",
  "Playing guitar",
  "Baking cookies",
  "Walking the dog",
  "Flying a kite",
  "Building a sandcastle",
  "Juggling",
  "Doing a cartwheel",
  "Taking a selfie",
  "Opening presents",
  "Trick-or-treating",
  "Making a snowman",
  "Watering plants",
  "Missing the bus",
  "Winning a race",
  "Dropping your phone",
  "Carrying groceries",
  // Movies & shows (well-known)
  "Star Wars",
  "Harry Potter",
  "The Lion King",
  "Frozen",
  "Toy Story",
  "Jurassic Park",
  "Spider-Man",
  "Batman",
  "Superman",
  "The Wizard of Oz",
  "Jaws",
  "E.T.",
  "Ghostbusters",
  "Finding Nemo",
  "Shrek",
  "The Simpsons",
  "Sesame Street",
  "SpongeBob SquarePants",
  "Game of Thrones",
  "Stranger Things",
  // Idioms & expressions
  "Piece of cake",
  "Break the ice",
  "When pigs fly",
  "The elephant in the room",
  "Let the cat out of the bag",
  "Kill two birds with one stone",
  "Spill the beans",
  "Under the weather",
  "Barking up the wrong tree",
  "Beat around the bush",
  "Costs an arm and a leg",
  "Cry over spilled milk",
  "Hold your horses",
  "Jump on the bandwagon",
  "The ball is in your court",
  "Throw in the towel",
  "Wild goose chase",
  "Zip your lip",
  // Nature & weather
  "Thunderstorm",
  "Rainbow",
  "Aurora borealis",
  "Tornado",
  "Earthquake",
  "Volcano erupting",
  "Waterfall",
  "Desert cactus",
  "Coral reef",
  "Iceberg",
  "Mushroom cloud",
  "Lightning bolt",
  "Snowflake",
  "Sand dune",
  "Geyser",
  "Earthworm",
  "Honeybee",
  "Spiderweb",
  "Sunflower field",
  "Cherry blossoms",
  // Sports & games
  "Basketball hoop",
  "Soccer goal",
  "Baseball mitt",
  "Bowling pins",
  "Pinata",
  "Dodgeball",
  "Ice hockey",
  "Surfing",
  "Ski jumping",
  "Golf hole-in-one",
  "Ping-pong",
  "Tug of war",
  "Hula hoop",
  "Jump rope",
  "Scuba diving",
  "Rock climbing",
  "Fishing rod",
  "Archery target",
  // Random nouns
  "Robot",
  "Alien spaceship",
  "Time machine",
  "Treasure chest",
  "Magic wand",
  "Crystal ball",
  "Flying carpet",
  "Dragon",
  "Unicorn",
  "Mermaid",
  "Vampire",
  "Zombie",
  "Wizard hat",
  "Knight in armor",
  "Pirate ship",
  "Submarine",
  "Helicopter",
  "Hot air balloon",
  "Rocket launch",
  "Satellite dish",
  "Microscope",
  "Light bulb",
  "Battery",
  "Solar panel",
  "Wind turbine",
  "Bridge drawbridge",
  "Skyscraper",
  "Elevator",
  "Escalator",
  "Vending machine",
  "ATM",
  "Shopping cart",
  "Wheelbarrow",
  "Stethoscope",
  "Ambulance",
  "Fire truck",
  "Police car",
  "School bus",
  "Train tunnel",
  "Airport runway",
  "Suitcase",
  "Passport",
  "Sleeping bag",
  "Flashlight",
  "Campfire",
  "Marshmallow roast",
  "Compass",
  "Binoculars",
  "Map folded wrong",
  "Lost hiker",
  "Birthday party hat",
  "Piñata stick",
  "Confetti cannon",
  "Balloon animal",
  "Face paint",
  "Roller coaster loop",
  "Ferris wheel",
  "Carousel horse",
  "Haunted mirror",
  "Jack-o-lantern",
  "Easter egg hunt",
  "Fireworks show",
  "New Year's countdown",
  "Alarm clock ringing",
  "Snooze button",
  "Coffee spill",
  "Remote control",
  "Wi-Fi router",
  "Printer jam",
  "Paperclip chain",
  "Stapler",
  "Rubber band ball",
  "Origami crane",
  "Lego tower",
  "Jigsaw puzzle",
  "Chess rook",
  "Domino chain reaction",
  "Royal flush",
  "Dice roll",
  "Vinyl record",
  "Karaoke night",
  "Air guitar solo",
  "Drum solo",
  "Violin case",
  "Marching band",
  "Parade float",
  "Red carpet",
  "Director's chair",
  "3D glasses",
  "Soda fountain",
  "Milk mustache",
  "Brain freeze",
  "Brainstorm",
  "Lightbulb moment",
  "Eureka",
  "Mad scientist",
  "Lab explosion",
  "Hamster wheel",
  "Goldfish bowl",
  "Walking on eggshells",
  "Seagull attack",
  "Bat cave",
  "Dinosaur bones",
  "Message in bottle",
  "Desert island",
  "Hammock",
  "Water balloon fight",
  "Slip and slide",
  "Garden gnome",
  "Lawn flamingo",
  "Garage sale",
  "Double rainbow",
  "Pot of gold"
];

export const PICTORY_CLUES: readonly PictionaryClue[] = CLUE_TEXTS.map((text, index) => ({
  id: `clue-${String(index).padStart(4, "0")}`,
  text
}));

export function pickPictionaryClue(usedIds: readonly string[]): PictionaryClue | null {
  const used = new Set(usedIds);
  const pool = PICTORY_CLUES.filter((c) => !used.has(c.id));
  const source = pool.length > 0 ? pool : [...PICTORY_CLUES];
  if (source.length === 0) {
    return null;
  }
  const pick = source[Math.floor(Math.random() * source.length)]!;
  return pick;
}
